steps:
  # 1. Fazer o Build da Imagem Docker a partir da pasta scripts
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/mlflow-etl-job:$TAG_NAME'
      - '-f'
      - 'Dockerfile_etl'
      - '.'

  # 2. Fazer o Push da Imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/mlflow-etl-job:$TAG_NAME'

  # 3. Atualizar o Cloud Run Job com a nova Imagem
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'mlflow-to-gcs-etl'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/mlflow-etl-job:$TAG_NAME'
      - '--region'
      - '$_REGION'

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'mlflow-docker'
  TAG_NAME: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
